steps:
  # Reservations
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "europe-west10-docker.pkg.dev/sleepr-437814/reservations/production", "-f", "apps/reservations/Dockerfile", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west10-docker.pkg.dev/sleepr-437814/reservations/production"]

  # Payments
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "europe-west10-docker.pkg.dev/sleepr-437814/payments/production", "-f", "apps/payments/Dockerfile", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west10-docker.pkg.dev/sleepr-437814/payments/production"]

  # Auth
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "europe-west10-docker.pkg.dev/sleepr-437814/auth/production", "-f", "apps/auth/Dockerfile", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west10-docker.pkg.dev/sleepr-437814/auth/production"]

  # Notifications
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "europe-west10-docker.pkg.dev/sleepr-437814/notifications/production", "-f", "apps/notifications/Dockerfile", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west10-docker.pkg.dev/sleepr-437814/notifications/production"]